# Region.delete_all
# Region.create!({uk_name: 'Вінницька'})
# Region.create!({uk_name: 'Волинська'})
# Region.create!({uk_name: 'Дніпропетровська'})
# Region.create!({uk_name: 'Донецька'})
# Region.create!({uk_name: 'Житомирська'})
# Region.create!({uk_name: 'Закарпатська'})
# Region.create!({uk_name: 'Запорізька'})
# Region.create!({uk_name: 'Івано-Франківська'})
# Region.create!({uk_name: 'Київська'})
# Region.create!({uk_name: 'Кіровоградська'})
# Region.create!({uk_name: 'Луганська'})
# Region.create!({uk_name: 'Львівська'})
# Region.create!({uk_name: 'Миколаївська'})
# Region.create!({uk_name: 'Одеська'})
# Region.create!({uk_name: 'Полтавська'})
# Region.create!({uk_name: 'Рівненська'})
# Region.create!({uk_name: 'Сумська'})
# Region.create!({uk_name: 'Тернопільська'})
# Region.create!({uk_name: 'Харківська'})
# Region.create!({uk_name: 'Херсонська'})
# Region.create!({uk_name: 'Хмельницька'})
# Region.create!({uk_name: 'Черкаська'})
# Region.create!({uk_name: 'Чернівецька'})
# Region.create!({uk_name: 'Чернігівська'})
# Region.create!({uk_name: 'Республіка Крим'})

City.find_each(&:save)
